apiVersion: apps/v1
kind: Deployment
metadata:
  name: finsights-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finsights
  template:
    metadata:
      labels:
        app: finsights
    spec:
      containers:
      - name: finsights-app
        image: <pshantiraj123>/finsights-app:latest
        ports:
        - containerPort: 8080
